INSERT INTO USERS (USERNAME, PASSWORD, ENABLED)
VALUES ('user', '{bcrypt}$2a$10$tiNTk0azCUKZi8htBTom8uLxkzytLq2C0J0TsflOUkBYjolH9WnBS', TRUE);

INSERT INTO AUTHORITIES (USERNAME, AUTHORITY)
VALUES ('user', 'ROLE_USER');